---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: default
      backend: local
      controls:
        - s3_bucket
        - s3_files

platforms:
  - name: terraform

suites:
  - name: default