---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  command_timeout: 1200
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: eks
      backend: local
      controls:
        - s3_bucket
        - s3_files
        - helloworld 

platforms:
  - name: terraform

suites:
  - name: eks